[command.connect]
	link="AT+WAPICT,1,APX,12345678,1"
	unlink="AT+WSDISCNCT"
	show-msg="AT"
	setting=["AT"]
	reset="AT"
	
[command.control]
	link-socket='AT+NCRECLNT=TCP,192.168.1.2,1234,1234'
	unlink-socket="AT+NSTOP,0"
	send="AT+SKSND=0,0,"
	recv="AT+SKRCV=0,0,1"
	msg="""
EEvTSV1$wA~w4u#LZ^zBXheL9G30%9#rVbD2isrusNBPQ^(YnFjSvs6fbWKKyvvLuqz^EKw&1zdqj1_LdH4Nyldzg7hWENtUu@R@A@^E@wRyFQoStkLrM~+7YE!~*a%sS7Pt#ujJ~PZUKYp8@olnHK*f^rYuWp_ku#O#aBjgSgN*xtnNWVh)T~6qvEPg9!h3J1z0jKG2$_WEO)1mAHc~tLO$ufj8OIU7Q*J5asbfLE60o3x!fGlO@Dt$Kg(uAYEITviQYqK@h$Pt(Q@bb!%z(DlyH+EDgUiUqI&6r6+)n3$%GxwydH)!qyPB2xczr!pYi$4LQjp0aq)BFS@#!1qGCHoE$lyjbs9M@~rLpWfr$9cR~VGW^*^kOfO^RuJBsJn1~^BjOho#tH8QWHt&$GjMPj~qLCNg6hhQbbU35Id3EOPdG^)$zyE734NDP#cgrV$TJ%*LZEpF%A3~^cI6DWbTl8ow&s3b6wtnbMg3^KPx#rcsJgAi$~U%qQB@tL^rw9*MgJo7m9r$uvS)UgtXJZSP
3S#n07)7Y@($OJU4XR6$@@p6Ms6fsGb$qIh@P#prO#l1C923+9FBGc^P^qkfy*!6GYLL(o2X+q1l^D5_KG!#nhI4rWh_bfScRgcaEZLsZ+6#sWjvS25_&T5zN~g19TgSaHpg(Vm96He+EyV!*U%U##d%$WwGk7UF_+mb5k)w&qWMRO^pUl7SOqyQ6zQBD@cwD2)3eKH5wpo*0mA@UXe9r1$k$&rgJL+NDiendo%hgjM%YH4aW&xtGhzYapD%apmKuh)4b$ZE&hxgd_d2QMY^gvi3%syBdJO+W8X_)6o32!si0M#p@Hv4Gk~5B3(REJYtktto1rbg@1zd47puaSUPBKyOU3Nx2Qdq(ZS3Ei~I(Mmf__aEhv#3#ghxv@7TwzVL8#SfBf07G$JMpW*j&LzDnc4qgs%a6TcRkHNe8uMHySHHfVEmk4wC7!ZgH+C&%FzR$4DLLvOKY(6Hu40m65b4TH6)12!zGq+Vl&+$)HypF_s3S9B)166RtTTrBn^MMoaAYpWV_z6aK$l6zW%)vGuv#KJcKm)UKU6e(J~wbr6pjmrXEDE(CVkMTgXcutW%cvofuT&e&FVMeUiX@Oz*q*aFh$ayu9qugE&iN9)Ym)96YjvnwUdmIZL@2sZa(C@hcKHv@aD^fes
nLs7La$H!@O0h#Bfu#nXBy@*Ir0%(GRzCoGWJZfA3e#roA^ZP1v$TvoJ!x7JiUP^DJkt#lMh^E^y)ilb!YcgmaQ*&*tpGKt)GQ(uYja&li%%LR_Qye%^FGWDUeNYGuQEpPL0u1VC9KVcx_VpAoqd!@7iO8$NRxkyxlsx_^CX!r@~csZFrV91y+V9(JLSxBQt_9$dMe(*RknXIuVvTx%zy1xq1e3dLG&Z@13L1PCKCQoYcsxu7E8FZIE3ll%flWp1UG++6ofD&MpkzJulJ0)BcxUVb8OEN9#!@w*K*m3vNOntB%G$2TJZm6wMlny#Yl7Xm(aLKm0jf4kQvr#9jA)~%$(6VoirZ)t#2_$D&SR^W1h%@hefvP1u8Rq9a@4L@G~HyzOnm37&a~y2L9xQXcqXyufUE498396&MVmPx(ZB_UR20Jq2kZ#3*~S&&S3nekTP77AsVlA4W0C!zPdLza2eZvzA4RXaWKdNYLchLEOsmbRxZDRqAY#H3_01Uhiiv1DLmtS93@)LGHCDWLLiKtNRbG)MDxY9BZ0w&%JXhMxizbLZpGV^3rm!FRtvaWN9G^iMIGtifmWCIOB
2s&+ZHJxJq&aY4f8LTAl)2dV5kpP49QgUyZ31MHAnHYRU!^IEwL3nMTO$1%@RqCm9_LAFVqs+2U!Ts2!nwZaQUo!Zh#87vd!STzHfBkm$Rm6IQKNs9C%cBwAAIyuh14CBGfyX3cx68TT4ac3C@a6B~xtE20bVwQ_q)Ctd3R8!fQLY$20yTGEWx+ND(qp$YBfU_6j_pdTuoepQs@PqAGsicNrdXC8xF^OaGVX8qA@!j8&RfFfOSi0qJluzeaMvv!GUU%p9N8(GH64ZHI95IldCWd^%qBaa~ApNHv_NppXc9jHm3csCSN2y(2K@OHY+2r1)dTb8QVx4qEynl0HZ71wdrIFXITB(G@82oUZD#CwbMB&oyyR0U1fhSHFp%uVZU7Bi^S7KMfD7)g0KV*54ho)HG$y~Ys4*Tu9LDXex2f18)$Uvip@hULJHsti~F6vKLsE+e5%XUYpn&^7hb5__58I%%DfNYii3oxOy4j~G#(HO08$3%*6t_ozw3hK9LKbtD(0sVrKyP~Zx@3$_6JBq*j3lYm&oa
ivBsf9Y#X~EHGa3!Nm(ms~Us&K9$Yu5@Q0OiVNi9S+lcZwGw1E2NwP$PeI3m$1Hwah9UyOYAN5^vJd8M7CpU72~5Md)+(sP_mZHU)BJTV%9JZ85*f%YOsMDwGFqj%NzJJbevwqqn&r0Gb#@ENifaVoeC$TbuSIp089)Z(~gm_rX5PxPk^cV5fnjIX^N+8M0ez$SV)uU@)nOSJatm4M@A~XAqJtA2Jwgk39v1J!#~%*T!$l1EWy&N3YT(g61%pazDX!)B$21I9($xwD*GQyepiB28Hf2RBwzNlJXtn&2F$swXdUj0bUq*%SW2K!ElRWC^FM(6l3_WeJuJe1lBq!zSSadE0*qo^w+fFeN_y*Tn+4cH1yPW+_BSLn50@W@ZeX_o&mX5cas1ZnE5rN)H2L8B+o#Bd4R!7t6oPD)M6fy*9%LtC)tm4o@K4fmPFNkM7Q2Kva51u1XQm$WhS#xdXXq*kPSdx(DnGw&+2Bd_~8~uOwC7K_L&2Q^Nm_1qILxpDqajTFws3Q5S
"""

[command.check]
	wlan="AT+WSCAN=3"
	uart="AT"

[setting]
	wlan-name="connected"
	[setting.ca]
		AS-path="cyg_AS.cer"
		STA-path="cyg_STA.cer"
	[setting.uart]
		name="COM15"
		baud=921600
		databit=8
		stopbit=1
		parity=0