[command.connect]
	link="AT+WJOIN"
	unlink="AT+WLEAV"
	show-msg="AT+LKSTT"
	setting=[
		"AT+WPRT=0",
		'AT+SSID="HC-WAPI"',
		'AT+KEY=1,1,0,""',
		"AT+NIP=0",		
	]
	reset="AT+Z"
	
[command.control]
	link-socket='AT+SKCT=0,0,"192.168.1.2",1234,1234'
	unlink-socket="AT+SKCLS="
	send="AT+SKSND="
	recv="AT+SKRCV="
	msg="hello"

[command.check]
	wlan="AT+WSCAN"
	uart="AT+UART"

[setting]
	wlan-name="HC-WAPI"
	[setting.ca]
		AS-path="cyg_AS.cer"
		STA-path="cyg_STA.cer"
	[setting.uart]
		name="COM13"
		baud=115200
		databit=8
		stopbit=1
		parity=0