/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hello.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "hello.pb-c.h"
void   hello__hello_request__init
                     (Hello__HelloRequest         *message)
{
  static const Hello__HelloRequest init_value = HELLO__HELLO_REQUEST__INIT;
  *message = init_value;
}
size_t hello__hello_request__get_packed_size
                     (const Hello__HelloRequest *message)
{
  assert(message->base.descriptor == &hello__hello_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hello__hello_request__pack
                     (const Hello__HelloRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hello__hello_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hello__hello_request__pack_to_buffer
                     (const Hello__HelloRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hello__hello_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hello__HelloRequest *
       hello__hello_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hello__HelloRequest *)
     protobuf_c_message_unpack (&hello__hello_request__descriptor,
                                allocator, len, data);
}
void   hello__hello_request__free_unpacked
                     (Hello__HelloRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hello__hello_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hello__hello_response__init
                     (Hello__HelloResponse         *message)
{
  static const Hello__HelloResponse init_value = HELLO__HELLO_RESPONSE__INIT;
  *message = init_value;
}
size_t hello__hello_response__get_packed_size
                     (const Hello__HelloResponse *message)
{
  assert(message->base.descriptor == &hello__hello_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hello__hello_response__pack
                     (const Hello__HelloResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hello__hello_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hello__hello_response__pack_to_buffer
                     (const Hello__HelloResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hello__hello_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hello__HelloResponse *
       hello__hello_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hello__HelloResponse *)
     protobuf_c_message_unpack (&hello__hello_response__descriptor,
                                allocator, len, data);
}
void   hello__hello_response__free_unpacked
                     (Hello__HelloResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hello__hello_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hello__hello_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Hello__HelloRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hello__hello_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange hello__hello_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hello__hello_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "hello.HelloRequest",
  "HelloRequest",
  "Hello__HelloRequest",
  "hello",
  sizeof(Hello__HelloRequest),
  1,
  hello__hello_request__field_descriptors,
  hello__hello_request__field_indices_by_name,
  1,  hello__hello_request__number_ranges,
  (ProtobufCMessageInit) hello__hello_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hello__hello_response__field_descriptors[1] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Hello__HelloResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hello__hello_response__field_indices_by_name[] = {
  0,   /* field[0] = message */
};
static const ProtobufCIntRange hello__hello_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hello__hello_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "hello.HelloResponse",
  "HelloResponse",
  "Hello__HelloResponse",
  "hello",
  sizeof(Hello__HelloResponse),
  1,
  hello__hello_response__field_descriptors,
  hello__hello_response__field_indices_by_name,
  1,  hello__hello_response__number_ranges,
  (ProtobufCMessageInit) hello__hello_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor hello__hello__method_descriptors[1] =
{
  { "SayHello", &hello__hello_request__descriptor, &hello__hello_response__descriptor },
};
const unsigned hello__hello__method_indices_by_name[] = {
  0         /* SayHello */
};
const ProtobufCServiceDescriptor hello__hello__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "hello.Hello",
  "Hello",
  "Hello__Hello",
  "hello",
  1,
  hello__hello__method_descriptors,
  hello__hello__method_indices_by_name
};
void hello__hello__say_hello(ProtobufCService *service,
                             const Hello__HelloRequest *input,
                             Hello__HelloResponse_Closure closure,
                             void *closure_data)
{
  assert(service->descriptor == &hello__hello__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void hello__hello__init (Hello__Hello_Service *service,
                         Hello__Hello_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &hello__hello__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
